services:
  test-all:
    build:
      context: .
      target: test
    command: npx vitest run --coverage

  test-unit:
    build:
      context: .
      target: test
    command: npx vitest run tests/unit

  test-integration:
    build:
      context: .
      target: test
    command: npx vitest run tests/integration
