version: "3.9"
services:
  test-unit:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: npx vitest run

  test-integration:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: npx vitest run tests/integration
